CREATE OR REPLACE PROCEDURE PLC_DWH.CONFIG_SCHEMA.SP_SILVER_INCREMENTAL_MERGE("P_SOURCE_SCHEMA" VARCHAR, "P_SOURCE_TABLE" VARCHAR, "P_TARGET_SCHEMA" VARCHAR, "P_RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE 
   V_SQL               STRING; 
   V_MERGE_SQL         STRING; 
   V_COLUMNS           STRING; 
   V_UPDATE_COLS       STRING; 
   V_INSERT_VALUES     STRING; 
   V_PK_COLUMNS        STRING; 
   V_PK_SELECT         STRING; 
   V_PK_JOIN           STRING; 
   V_BATCH_ID          STRING := P_RUN_ID; 
   V_SOURCE_COUNT      NUMBER DEFAULT 0; 
   V_ROWS_AFFECTED     NUMBER DEFAULT 0; 
   V_START_TIME        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(); 
   V_END_TIME          TIMESTAMP_NTZ; 
   V_ERROR_MSG         STRING; 
   V_DUPLICATE_COUNT   NUMBER DEFAULT 0; 
   V_CUR_EXISTS        NUMBER DEFAULT 0; 
   V_EVOLVE_RESULT     VARIANT; 
 
   -- METADATA VARIABLES 
   V_ADD_COL           NUMBER DEFAULT 0; 
   V_WIDEN_COL         NUMBER DEFAULT 0; 
   V_META_JSON         VARIANT; 
 
   RS_COMMON           RESULTSET; 
 
BEGIN 
   -------------------------------------------------------------------- 
   -- Step 1: Get PK columns from our PLC Config Table 
   -------------------------------------------------------------------- 
   BEGIN 
       SELECT PRIMARY_KEY_COLUMNS 
       INTO :V_PK_COLUMNS 
       FROM PLC_DWH.CONFIG_SCHEMA.INGESTION_CONFIG 
       WHERE TARGET_SNOWFLAKE_TABLE = :P_SOURCE_TABLE 
       LIMIT 1; 
   EXCEPTION 
       WHEN OTHER THEN 
           V_PK_COLUMNS := NULL; 
   END; 
 
   IF (V_PK_COLUMNS IS NULL OR TRIM(V_PK_COLUMNS) = '''') THEN 
       V_END_TIME := CURRENT_TIMESTAMP(); 
       V_ERROR_MSG := ''PRIMARY_KEY_COLUMNS not configured''; 
       INSERT INTO PLC_DWH.CONFIG_SCHEMA.LOAD_AUDIT_LOG (ADF_PIPELINE_RUN_ID, SOURCE_SCHEMA, SOURCE_TABLE, TARGET_SCHEMA, TARGET_TABLE, START_TIME, END_TIME, SOURCE_ROW_COUNT, ROWS_AFFECTED, STATUS, ERROR_MESSAGE, LOAD_METADATA) 
       SELECT :V_BATCH_ID, :P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA, :P_SOURCE_TABLE, :V_START_TIME, :V_END_TIME, 0, 0, ''SKIPPED'', :V_ERROR_MSG, NULL; 
       RETURN ''SKIPPED - '' || V_ERROR_MSG; 
   END IF; 
 
   -------------------------------------------------------------------- 
   -- Step 2: Check CUR (Silver) table exists (Case-Insensitive) 
   -------------------------------------------------------------------- 
   SELECT COUNT(*) INTO :V_CUR_EXISTS 
   FROM PLC_DWH.INFORMATION_SCHEMA.TABLES 
   WHERE UPPER(TABLE_SCHEMA) = UPPER(:P_TARGET_SCHEMA) 
     AND UPPER(TABLE_NAME) = UPPER(:P_SOURCE_TABLE); 
 
   IF (V_CUR_EXISTS = 0) THEN 
       V_SQL := ''CREATE TABLE PLC_DWH."'' || REPLACE(P_TARGET_SCHEMA, ''"'', ''""'') || ''"."'' || REPLACE(P_SOURCE_TABLE, ''"'', ''""'') || ''" AS SELECT * FROM PLC_DWH."'' || REPLACE(P_SOURCE_SCHEMA, ''"'', ''""'') || ''"."'' || REPLACE(P_SOURCE_TABLE, ''"'', ''""'') || ''" WHERE 1=0''; 
       EXECUTE IMMEDIATE V_SQL; 
   END IF; 
 
   -------------------------------------------------------------------- 
   -- Step 2.5: Schema Evolution 
   -------------------------------------------------------------------- 
   BEGIN 
       CALL PLC_DWH.CONFIG_SCHEMA.SP_EVOLVE_SILVER_SCHEMA(:P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA); 
       SELECT $1 INTO :V_EVOLVE_RESULT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())); 
 
       -- Extract stats for final logging 
       V_ADD_COL := COALESCE(GET_PATH(:V_EVOLVE_RESULT, ''added_columns'')::NUMBER, 0); 
       V_WIDEN_COL := COALESCE(GET_PATH(:V_EVOLVE_RESULT, ''widened_columns'')::NUMBER, 0); 
 
   EXCEPTION 
       WHEN OTHER THEN 
           INSERT INTO PLC_DWH.CONFIG_SCHEMA.LOAD_AUDIT_LOG (ADF_PIPELINE_RUN_ID, SOURCE_SCHEMA, SOURCE_TABLE, TARGET_SCHEMA, TARGET_TABLE, START_TIME, END_TIME, SOURCE_ROW_COUNT, ROWS_AFFECTED, STATUS, ERROR_MESSAGE, LOAD_METADATA) 
           SELECT :V_BATCH_ID, :P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA, :P_SOURCE_TABLE, :V_START_TIME, CURRENT_TIMESTAMP(), 0, 0, ''FAILED_SCHEMA_EVOLUTION'', :SQLERRM, NULL; 
           RETURN ''FAILED - '' || SQLERRM; 
   END; 
 
   -------------------------------------------------------------------- 
   -- Step 3: Source count 
   -------------------------------------------------------------------- 
   V_SQL := ''SELECT COUNT(*) FROM PLC_DWH."'' || REPLACE(P_SOURCE_SCHEMA, ''"'', ''""'') || ''"."'' || REPLACE(P_SOURCE_TABLE, ''"'', ''""'') || ''"''; 
   EXECUTE IMMEDIATE V_SQL; 
   SELECT $1 INTO :V_SOURCE_COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())); 
 
   -------------------------------------------------------------------- 
   -- Step 4: Build Exact-Case Column Lists 
   -------------------------------------------------------------------- 
   CREATE OR REPLACE TEMPORARY TABLE TEMP_PK_COLS AS SELECT UPPER(TRIM(VALUE)) AS PK_COLUMN FROM TABLE(SPLIT_TO_TABLE(:V_PK_COLUMNS, '','')); 
 
   CREATE OR REPLACE TEMPORARY TABLE TEMP_COMMON_ACTIVE_COLS AS 
   SELECT c.COLUMN_NAME, c.ORDINAL_POSITION, CASE WHEN pk.PK_COLUMN IS NOT NULL THEN TRUE ELSE FALSE END AS IS_PK 
   FROM PLC_DWH.INFORMATION_SCHEMA.COLUMNS c 
   JOIN PLC_DWH.INFORMATION_SCHEMA.COLUMNS s ON UPPER(c.COLUMN_NAME) = UPPER(s.COLUMN_NAME) 
   LEFT JOIN TEMP_PK_COLS pk ON UPPER(c.COLUMN_NAME) = pk.PK_COLUMN 
   WHERE UPPER(c.TABLE_SCHEMA) = UPPER(:P_TARGET_SCHEMA) AND UPPER(c.TABLE_NAME) = UPPER(:P_SOURCE_TABLE) 
     AND UPPER(s.TABLE_SCHEMA) = UPPER(:P_SOURCE_SCHEMA) AND UPPER(s.TABLE_NAME) = UPPER(:P_SOURCE_TABLE); 
 
   V_SQL := '' 
       SELECT 
           LISTAGG(''''"'''' || REPLACE(COLUMN_NAME, ''''"'''', ''''""""'''') || ''''"'''', '''','''') WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS COLUMNS_LIST, 
           LISTAGG(''''SRC."'''' || REPLACE(COLUMN_NAME, ''''"'''', ''''""""'''') || ''''"'''', '''','''') WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS INSERT_VALUES_LIST, 
           LISTAGG(CASE WHEN IS_PK = FALSE THEN ''''"'''' || REPLACE(COLUMN_NAME, ''''"'''', ''''""""'''') || ''''" = SRC."'''' || REPLACE(COLUMN_NAME, ''''"'''', ''''""""'''') || ''''"'''' END, '''','''') WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS UPDATE_COLS_LIST, 
           LISTAGG(CASE WHEN IS_PK = TRUE THEN ''''"'''' || REPLACE(COLUMN_NAME, ''''"'''', ''''""""'''') || ''''"'''' END, '''','''') WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS PK_SELECT_LIST, 
           LISTAGG(CASE WHEN IS_PK = TRUE THEN ''''TGT."'''' || REPLACE(COLUMN_NAME, ''''"'''', ''''""""'''') || ''''" = SRC."'''' || REPLACE(COLUMN_NAME, ''''"'''', ''''""""'''') || ''''"'''' END, '''' AND '''') WITHIN GROUP (ORDER BY ORDINAL_POSITION) AS PK_JOIN_LIST 
       FROM TEMP_COMMON_ACTIVE_COLS 
   ''; 
 
   RS_COMMON := (EXECUTE IMMEDIATE :V_SQL); 
   LET CUR_COMMON CURSOR FOR RS_COMMON; 
   FOR REC_COMMON IN CUR_COMMON DO 
       V_COLUMNS := REC_COMMON.COLUMNS_LIST; 
       V_INSERT_VALUES := REC_COMMON.INSERT_VALUES_LIST; 
       V_UPDATE_COLS := REC_COMMON.UPDATE_COLS_LIST; 
       V_PK_SELECT := REC_COMMON.PK_SELECT_LIST; 
       V_PK_JOIN := REC_COMMON.PK_JOIN_LIST; 
   END FOR; 
 
   DROP TABLE IF EXISTS TEMP_COMMON_ACTIVE_COLS; 
   DROP TABLE IF EXISTS TEMP_PK_COLS; 
 
   IF (V_PK_JOIN IS NULL OR V_PK_JOIN = '''') THEN 
       V_END_TIME := CURRENT_TIMESTAMP(); 
       V_ERROR_MSG := ''Could not build PK join condition. Verify PK exists in source.''; 
       INSERT INTO PLC_DWH.CONFIG_SCHEMA.LOAD_AUDIT_LOG (ADF_PIPELINE_RUN_ID, SOURCE_SCHEMA, SOURCE_TABLE, TARGET_SCHEMA, TARGET_TABLE, START_TIME, END_TIME, SOURCE_ROW_COUNT, ROWS_AFFECTED, STATUS, ERROR_MESSAGE, LOAD_METADATA) 
       SELECT :V_BATCH_ID, :P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA, :P_SOURCE_TABLE, :V_START_TIME, :V_END_TIME, :V_SOURCE_COUNT, 0, ''SKIPPED'', :V_ERROR_MSG, NULL; 
       RETURN ''SKIPPED - '' || V_ERROR_MSG; 
   END IF; 
 
   IF (V_INSERT_VALUES IS NOT NULL) THEN V_INSERT_VALUES := REGEXP_REPLACE(V_INSERT_VALUES, ''SRC."_INGESTED_AT"'', ''CURRENT_TIMESTAMP()'', 1, 0, ''i''); END IF; 
   IF (V_UPDATE_COLS IS NOT NULL) THEN V_UPDATE_COLS := REGEXP_REPLACE(V_UPDATE_COLS, ''"_INGESTED_AT" = SRC."_INGESTED_AT"'', ''"_INGESTED_AT" = CURRENT_TIMESTAMP()'', 1, 0, ''i''); END IF; 
 
   -------------------------------------------------------------------- 
   -- Step 5: Duplicate PK check 
   -------------------------------------------------------------------- 
   V_SQL := ''SELECT COUNT(*) FROM (SELECT '' || V_PK_SELECT || '', COUNT(*) AS CNT FROM PLC_DWH."'' || REPLACE(P_SOURCE_SCHEMA, ''"'', ''""'') || ''"."'' || REPLACE(P_SOURCE_TABLE, ''"'', ''""'') || ''" GROUP BY '' || V_PK_SELECT || '' HAVING COUNT(*) > 1)''; 
   BEGIN 
       EXECUTE IMMEDIATE V_SQL; 
       SELECT $1 INTO :V_DUPLICATE_COUNT FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())); 
   EXCEPTION WHEN OTHER THEN V_DUPLICATE_COUNT := 0; 
   END; 
 
   IF (V_DUPLICATE_COUNT > 0) THEN 
       V_END_TIME := CURRENT_TIMESTAMP(); 
       V_ERROR_MSG := ''DUPLICATE_PK: '' || TO_VARCHAR(V_DUPLICATE_COUNT) || '' duplicate primary key combinations found. Use FULL LOAD.''; 
       INSERT INTO PLC_DWH.CONFIG_SCHEMA.LOAD_AUDIT_LOG (ADF_PIPELINE_RUN_ID, SOURCE_SCHEMA, SOURCE_TABLE, TARGET_SCHEMA, TARGET_TABLE, START_TIME, END_TIME, SOURCE_ROW_COUNT, ROWS_AFFECTED, STATUS, ERROR_MESSAGE, LOAD_METADATA) 
       SELECT :V_BATCH_ID, :P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA, :P_SOURCE_TABLE, :V_START_TIME, :V_END_TIME, :V_SOURCE_COUNT, 0, ''SKIPPED'', :V_ERROR_MSG, NULL; 
       RETURN ''SKIPPED - '' || V_ERROR_MSG; 
   END IF; 
 
   -------------------------------------------------------------------- 
   -- Step 6: Build MERGE SQL 
   -------------------------------------------------------------------- 
   V_MERGE_SQL := ''MERGE INTO PLC_DWH."'' || REPLACE(P_TARGET_SCHEMA, ''"'', ''""'') || ''"."'' || REPLACE(P_SOURCE_TABLE, ''"'', ''""'') || ''" TGT USING PLC_DWH."'' || REPLACE(P_SOURCE_SCHEMA, ''"'', ''""'') || ''"."'' || REPLACE(P_SOURCE_TABLE, ''"'', ''""'') || ''" SRC ON '' || V_PK_JOIN; 
 
   IF (V_UPDATE_COLS IS NOT NULL AND TRIM(V_UPDATE_COLS) <> '''') THEN 
       V_MERGE_SQL := V_MERGE_SQL || '' WHEN MATCHED THEN UPDATE SET '' || V_UPDATE_COLS; 
   END IF; 
   V_MERGE_SQL := V_MERGE_SQL || '' WHEN NOT MATCHED THEN INSERT ('' || V_COLUMNS || '') VALUES ('' || V_INSERT_VALUES || '')''; 
 
   -------------------------------------------------------------------- 
   -- Step 7: Execute MERGE 
   -------------------------------------------------------------------- 
   BEGIN 
       EXECUTE IMMEDIATE V_MERGE_SQL; 
       V_ROWS_AFFECTED := SQLROWCOUNT; 
       V_END_TIME := CURRENT_TIMESTAMP(); 
 
       -- Build the JSON Metadata Object for logging 
       V_META_JSON := OBJECT_CONSTRUCT( 
           ''load_type'', ''INCREMENTAL_MERGE'', 
           ''added_columns'', V_ADD_COL, 
           ''widened_columns'', V_WIDEN_COL, 
           ''evolve_status'', COALESCE(GET_PATH(:V_EVOLVE_RESULT, ''status'')::STRING, ''SUCCESS'') 
       ); 
 
       INSERT INTO PLC_DWH.CONFIG_SCHEMA.LOAD_AUDIT_LOG (ADF_PIPELINE_RUN_ID, SOURCE_SCHEMA, SOURCE_TABLE, TARGET_SCHEMA, TARGET_TABLE, START_TIME, END_TIME, SOURCE_ROW_COUNT, ROWS_AFFECTED, STATUS, ERROR_MESSAGE, LOAD_METADATA) 
       SELECT :V_BATCH_ID, :P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA, :P_SOURCE_TABLE, :V_START_TIME, :V_END_TIME, :V_SOURCE_COUNT, :V_ROWS_AFFECTED, ''SUCCESS'', NULL, :V_META_JSON; 
 
       RETURN ''SUCCESS - '' || V_ROWS_AFFECTED || '' rows merged''; 
   EXCEPTION WHEN OTHER THEN 
       V_ERROR_MSG := LEFT(SQLERRM, 1500); V_END_TIME := CURRENT_TIMESTAMP(); 
       INSERT INTO PLC_DWH.CONFIG_SCHEMA.LOAD_AUDIT_LOG (ADF_PIPELINE_RUN_ID, SOURCE_SCHEMA, SOURCE_TABLE, TARGET_SCHEMA, TARGET_TABLE, START_TIME, END_TIME, SOURCE_ROW_COUNT, ROWS_AFFECTED, STATUS, ERROR_MESSAGE, LOAD_METADATA) 
       SELECT :V_BATCH_ID, :P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA, :P_SOURCE_TABLE, :V_START_TIME, :V_END_TIME, :V_SOURCE_COUNT, 0, ''FAILED'', :V_ERROR_MSG, NULL; 
       RETURN ''FAILED - '' || V_ERROR_MSG; 
   END; 
 
EXCEPTION 
   WHEN OTHER THEN 
       V_ERROR_MSG := LEFT(SQLERRM, 1500); V_END_TIME := CURRENT_TIMESTAMP(); 
       DROP TABLE IF EXISTS TEMP_COMMON_ACTIVE_COLS; DROP TABLE IF EXISTS TEMP_PK_COLS; 
       INSERT INTO PLC_DWH.CONFIG_SCHEMA.LOAD_AUDIT_LOG (ADF_PIPELINE_RUN_ID, SOURCE_SCHEMA, SOURCE_TABLE, TARGET_SCHEMA, TARGET_TABLE, START_TIME, END_TIME, SOURCE_ROW_COUNT, ROWS_AFFECTED, STATUS, ERROR_MESSAGE, LOAD_METADATA) 
       SELECT :V_BATCH_ID, :P_SOURCE_SCHEMA, :P_SOURCE_TABLE, :P_TARGET_SCHEMA, :P_SOURCE_TABLE, :V_START_TIME, :V_END_TIME, :V_SOURCE_COUNT, 0, ''FAILED'', :V_ERROR_MSG, NULL; 
       RETURN ''FAILED - '' || V_ERROR_MSG; 
END; 
';